---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80 # The service's port for internal traffic
      targetPort: 80 # Which port on the pod to connect to
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: example-app-helm
spec:
  parentRefs:
    - name: nginx-gateway-fabric
      sectionName: http
  rules:
    - matches:
        - headers:
            - name: host
              value: example-app-helm.127.0.0.1.nip.io
      backendRefs:
        - name: nginx
          port: 80